USE DCLN;
SELECT * FROM DCTLN;

### REMOVE DUPLICATES AS PER DESCRIPTION 
    uniquely assigned : InvoiceNo,StockCode,CustomerID ###

### INSIGHTS 1: INVOICE_STATUS ###

SELECT INVOICE_STATUS, COUNT(INVOICE_STATUS) AS "COUNT" FROM DCTLN 
GROUP BY INVOICE_STATUS ;

### INSIGHTS 2: QUANTITY AND COUNTRY ###

SELECT Country, COUNT(Quantity) AS "TOTAL QUANTITY" 
FROM DCTLN 
WHERE INVOICE_STATUS = 'COMPLETED'
GROUP BY Country;

### INSIGHTS 3: PRICE AND COUNTRY ###

SELECT Country, SUM(Price) AS "REVENUE" 
FROM DCTLN 
WHERE INVOICE_STATUS = 'COMPLETED'
GROUP BY Country;

### INSIGHTS 4: TOP SELL INVOICE ###

SELECT Invoice, price 
FROM DCTLN 
WHERE INVOICE_STATUS = 'COMPLETED' 
ORDER BY price DESC;

### INSIGHTS 5: TOP SELL QTY DESCRIPTION ITEM ###

SELECT Description, Quantity 
FROM DCTLN 
WHERE INVOICE_STATUS = 'COMPLETED' 
ORDER BY Quantity DESC;

### INSIGHTS 6: TOP QTY DESCRIPTION ITEM ###

SELECT Description , COUNT(price) AS "TOP_REVENUE" 
FROM DCTLN 
WHERE INVOICE_STATUS = 'COMPLETED' 
GROUP BY Description
ORDER BY TOP_REVENUE  DESC;
